---
- name: Test restore oracle database.
  hosts: oracleservers
  vars_files:
    - "{{ WORKSPACE }}/restoreORACLE/ansible/external_vars.yaml"
  remote_user: oracle  
  vars:
    ansible_sudo_password: oracle123
    ansible_password: {{ oraclepass }}

  tasks:

  - name: Basic usage
    ansible.builtin.debug:
      msg: "'{{ WORKSPACE }}' WORKSPACE env "

  - name: Create a directory if it does not exist
    file:
      path: "{{ remote_path }}"
      state: directory
      mode: '0755'

  - name: Copy scripts to the remote host
    template: 
      src: "{{ WORKSPACE }}/restoreORACLE/database/scripts/restoreDB.sh"
      dest: "{{ remote_path }}"
      mode: '0700'

  - name: run
    shell: "{{ remote_path }}/restoreDB.sh"
    register: out

  - debug: 
     var: out.stdout_lines

