pipeline {
    agent any

    parameters {
        string(name: "ORACLESID", defaultValue: "COREP_DR", trim: true, description: "ORACLE DATABASE SID")
    }

    stages {
        stage('Checkout') {
            steps {
                git branch:'main', url: 'https://github.com/pedromorenogcs/pruebasjenkins.git'
            }
        }
         stage('Ansible') {
             steps {
                  ansiblePlaybook inventory: 'workshop/ansible/inventory.ini', playbook: 'workshop/ansible/cpConfig.yaml'
            }
        }
        
    }
}
