# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "spox/ubuntu-arm"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.11"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "vmware_desktop" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
#   config.vm.provision "shell", inline: <<-SHELL
#sudo -u vagrant echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCpLBJPIyf3/JAojsSR+YThXxZ0nowHlIo7YHHKqBnR1B/zbOPf9j4GteJubqM69BS8HK9wOL0G8ABzfoEuuFWtSPDh5MhaY21/w40m6+EHy5uaMzZAwCqaBhC53jyaeRQ0jemjVwkRVpz3nPPGTWkU+bAKNYaVCW148OogWFKVOPRk9KBResP97yZ9D/pEwuowBD8Rdalqz9ST36ABu1LtpVFmBGc4CE1tr2XWO/Shna82sMTRyZGNbV/u2yJPITHl2eRHYHDuI+hLEgFLOmO4NiVAVcycmMRcCOccUvvfbhcpGsqyzb/k1u9vXZ86O0K/H+IkpbDfpaOg5iDzIY9134yFOAKVFkGlOb20pwvEIn5DfxU80ooeM0n6nu3qOFmZ7GWNp9CHVJ4VmNmgGoXTg66ApDfqUNkevAQVGvaD+22u3ElMiyMIYnQTettgiSuyuVNwwP5BEn0Khs4fLT+T/AU9KZbKT0hR3BMUSvBWKUzyL977akbFqk0vwwRTM+k= jenkins@vagrant" > /home/vagrant/.ssh/authorized_keys
#   SHELL
end
