---
- hosts: webserver
  become: yes
  remote_user: vagrant
  tasks:
   - name: Install the latest version of Apache and MariaDB
     ansible.builtin.apt:
       pkg:
         - apache2
         - php
         - libapache2-mod-php
