---
- hosts: webserver
  vars_files:
    - "{{ lookup('ansible.builtin.env', 'WORKSPACE') }}/ansible/external_vars.yaml"
  become: yes
  remote_user: vagrant
  tasks:
   - name: Copy file with owner and permissions
     ansible.builtin.copy:
       src: /var/lib/jenkins/workspace/pj1git/web/000-default.conf
       dest: /etc/apache2/sites-available/
       owner: root
       group: root
       mode: '0644'

   - name: Copy file with owner and permissions
     ansible.builtin.copy:
       src: "{{ workspace }}/web/index.html"
       dest: /var/www/html/
       owner: root
       group: root
       mode: '0644'
